[template]
# incoming-hooks = ["Contentful"]

[template.environment]
# # GOOGLE ANALYTICS
# GOOGLE_ANALYTICS_ID="UA---------"
# # CLOUDINARY
# CLOUD_NAME="----------"
# API_KEY="----------"
# API_SECRET="--------"
